name: CI

on:
  push:
    paths:
      - 'browser/**/*'
      - 'functions/**/*'
      - 'scripts/**/*'
      - '*.json'
      - '*.toml'
      - '.github/workflows/ci.yml'
    branches:
      - '**'
    tags:
      - '*.*.*'
  workflow_dispatch:

env:
  ARTIFACT_NAME: oauth-demo

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm clean-install

      - name: Lint code
        run: npm run lint

      - name: Build project
        run: npm run build

      - name: Upload browser artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: browser/

  deploy-github:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-22.04
    if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
    needs: build
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deploy-to-pages.outputs.page_url }}
    concurrency:
      group: github-pages
      cancel-in-progress: false
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup GitHub Pages
        id: setup-pages
        uses: actions/configure-pages@v3

      - name: Download browser artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: browser

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: browser

      - name: Deploy to GitHub Pages
        id: deploy-to-pages
        uses: actions/deploy-pages@v2

  deploy-cloudflare:
    name: Deploy to Cloudflare Pages
    runs-on: ubuntu-22.04
    if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
    needs: build
    permissions:
      contents: read
      deployments: write
    environment:
      name: cloudflare-pages
      url: ${{ steps.deploy-to-pages.outputs.url }}
    concurrency:
      group: cloudflare-pages
      cancel-in-progress: false
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Download browser artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: browser

      - name: Deploy to Cloudflare Pages
        id: deploy-to-pages
        uses: cloudflare/pages-action@v1
        with:
          directory: browser
          projectName: oauth-demo
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
